# Generated by Django 4.1.2 on 2023-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_avatar',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Google Drive Image Id'),
        ),
        migrations.AlterField(
            model_name='homedetails',
            name='avatar_img',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Google Drive Image Id'),
        ),
        migrations.AlterField(
            model_name='languagesicons',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, verbose_name='language Icon Image:(icons8.com)'),
        ),
        migrations.AlterField(
            model_name='mycontact',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Info (eg: umaveena.alvas@gmail.com)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='about_avatar',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Google Drive Image Id'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_used',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='servicesoffred',
            name='icon_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Google Drive Image Id'),
        ),
    ]
